version: '3.8'

services:
  back:
    build: ./
    container_name: site
    env_file:
      - .env
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 trainingmanager.wsgi:application
    volumes:
      - ./:/app
      - ./data/static:/app/static
      - ./data/media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000"

  bot:
    build: ./
    container_name: trackerbot
    env_file:
      - .env
    restart: always
    command: python -m bot.main
    volumes:
      - ./:/app
    depends_on:
      - back

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - back
